fix: atualizando projeto
rebecccruz/projeto_integrador pull request #43
Opened 2022-08-12 20:35 UTC by laridevmeli

Minha branch estava com problemas, precisei ajustar e estou colocando a minha parte em desenvolvimento.

2022-08-12 20:53 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/dto/AdvertisementDTO.java
> +    private Long costumerId;
Tem que ser customerId.

2022-08-12 20:53 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/dto/CustomerDTO.java
> +    @JsonProperty("costumer_name")
Arrumar para customer_name.

2022-08-12 20:54 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/mapper/ICustomerMapper.java
> +    CustomerDTO mappingCostumerModelToCostumerDTO(Customer costumer);
Arrumar o nome da classe instanciada para customer.

2022-08-12 20:54 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/mapper/ICustomerMapper.java
> +    Customer mappingCostumerDTOToCostumerModel(CustomerDTO dto);
Alterar para mapping CustumerDTOToCostumerModel.

2022-08-12 20:55 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/model/Customer.java
> +    @OneToMany(mappedBy = "costumer")
Arrumar o mappedBy para customer.

2022-08-12 20:56 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/model/Customer.java
> +    @JsonIgnoreProperties("costumer")
Arrumar para customer.

2022-08-12 20:57 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/model/Order.java
> +    @JoinColumn(name = "costumer_id", nullable = false)
Alterar o JoinColumn name para custumer_id.

2022-08-12 20:57 UTC, evycoliveira commented on src/main/java/br/com/dh/meli/projeto_integrador/model/Order.java
> +    private Customer costumer;
Alterar para private Customer custumer.

2022-08-13 12:11 UTC, evycoliveira requested changes
Revisar se em todas as classe que Customer é usado, o nome está escrito corretamente.

2022-08-13 13:07 UTC, aborgssouzameli requested changes
Bom dia. Parabéns pelo código. Das minhas reviews somente tirar linhas em brancos, por favor.
Desde já, agradeço.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/dto/CustomerDTO.java
> +
Bom dia. Por favor eliminar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/model/Customer.java
> +
Bom dia. Por favor eliminar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/model/Order.java
> +
Bom dia. Por favor retirar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/service/CostumerService.java
> +
Bom dia. Por favor retirar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/service/ShoppingCartService.java
> +
Bom dia. Por favor retirar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/service/ShoppingCartService.java
> +
Bom dia. Por favor retirar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/service/ShoppingCartService.java
> +
Bom dia. Por favor retirar linha em branco. Obrigado.

2022-08-13 13:07 UTC, aborgssouzameli commented on src/main/java/br/com/dh/meli/projeto_integrador/service/ShoppingCartService.java
> +
Bom dia. Por favor retirar linha em branco. Obrigado.

2022-08-13 21:04 UTC, closed without merging